# Site settings
title: flycarl's Blog
email: flyucarl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hello friend~, welcome to my blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flycarl.github.io" # the base hostname & protocol for your site
twitter_username: flyucarl
github_username: flycarl

# Build settings
markdown: kramdown
